import React from "react";
import "../css/Home.css";
import Avatar from "../images/avatar.svg";
const arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15];
const Home = () => {
	return (
		<div className='home-cont'>
			<div className='navbar'>
				<div className='nearby'>NEARBY ORDERS</div>
				<div className='nav-right'>
					<div className='create-btn'>Create Order</div>
					<div className='filter'>filter</div>
					<div className='logout'>Log out</div>
				</div>
			</div>
			<div className='home'>
				<div className='table'>
					<div>
						<div className='tab-header'>
							<div className='gen'>GENERATED BY</div>
							<div className='title'>TITLE</div>
							<div className='category'>CATGORY</div>
							<div className='points'>POINTS</div>
							<div className='action'>ACTION</div>
						</div>
						<hr className='divider' />
					</div>
					<div className='table-body'>
						{arr.map((i) => (
							<div key={i}>
								<div className='order-row'>
									<div className='gen'>
										<div>
											<img src={Avatar} />
										</div>
										<div className='gen-text'>Generated by whom</div>
									</div>
									<div className='title'>Daily needs list</div>
									<div className='category'>Category</div>
									<div className='points'>Ponits we get</div>
									<div className='action'>Action</div>
								</div>
								<hr className='divider' />
							</div>
						))}
					</div>
				</div>
			</div>
		</div>
	);
};

export default Home;
